
export const entradaTypes = {
    // GETALL
    REQ_GET_ENTRADA: 'REQ_GET_ENTRADA',
    SUCCESS_GET_ENTRADA: 'SUCCESS_GET_ENTRADA',
    FAIL_GET_ENTRADA: 'FAIL_GET_ENTRADA',

    //UPDATE
    REQ_UPDATE_ENTRADA: 'REQ_UPDATE_ENTRADA',
    SUCCESS_UPDATE_ENTRADA: 'SUCCESS_UPDATE_ENTRADA',
    FAIL_UPDATE_ENTRADA: 'FAIL_UPDATE_ENTRADA',
    RESET_UPDATE_ENTRADA: 'RESET_UPDATE_ENTRADA',

    //DELETE
    REQ_DELETE_ENTRADA: 'REQ_DELETE_ENTRADA',
    SUCCESS_DELETE_ENTRADA: 'SUCCESS_DELETE_ENTRADA',
    FAIL_DELETE_ENTRADA: 'FAIL_DELETE_ENTRADA',
    RESET_DELETE_ENTRADA: 'RESET_DELETE_ENTRADA',

    //INSERT
    REQ_INSERT_ENTRADA: 'REQ_INSERT_ENTRADA',
    SUCCESS_INSERT_ENTRADA: 'SUCCESS_INSERT_ENTRADA',
    FAIL_INSERT_ENTRADA: 'FAIL_INSERT_ENTRADA',
    RESET_INSERT_ENTRADA: 'RESET_INSERT_ENTRADA',

    REQ_ONE_ENTRADA: "REQ_ONE_ENTRADA",
    SUCCESS_ONE_ENTRADA: "SUCCESS_ONE_ENTRADA",
    FAIL_ONE_ENTRADA: "FAIL_ONE_ENTRADA"
}
